### ISSUE TITLE
LineageOS Bq Aquaris E4.5 - Sim not detected

### ISSUE THREAD

**Issue by pinplex** [Pablito2020/kernel_cyanogenmod_13_krillin#1]
Hola Pablito, muchisimas gracias por tu trabajo! 
Until yesterday I used your CM12 ROM on my E4.5. It worked very well. Then I upated to your recently uploaded LineageOS ROM (including OTA - Wow!). Everything works fine expect the fact that my SIM is not detected! What can I do?
Muchos Saludos, Alex

**Comment by Pablito2020** [comment]
Where did you download the rom? AndroidFIleHost? 
Cheers

**Comment by pinplex** [comment]
Yes, androidfilehost.com. Btw, I use the Bq E4.5 Ubuntu Edition. Also, for CM13 the SIM could not be detected.

**Comment by Pablito2020** [comment]
Maybe is because of the device (that is the ubuntu edition).
ANyway, if you can take logcat 
(in a shell, make: adb logcat > sim.txt)
It will be usefull for sure!

PS: If you downgrade to the stock kitkat rom, did you have RIL (SIM) working or not?
Wifi is working for you in the stock kitkat rom too?
What rom did you have until Lineage OS 13.0, my cm12.0? If I remember I didn't update any cm12.0 for public... Just for proving and it still beta... Can you show me the rom that you were?

**Comment by pinplex** [comment]
Yes, for stock kitkat rom I have both working, SIM and Wifi. Also for the CM12 rom, everything worked.
Attached is the logcat output:
[sim.txt](https://github.com/Pablito2020/android_kernel_mediatek_krillin/files/998560/sim.txt)

**Comment by Pablito2020** [comment]
But wich cm12 rom... Can you atach  link?

**Comment by pinplex** [comment]
I took the ROM from [here](http://www.htcmania.com/showthread.php?t=1060364).

**Comment by Pablito2020** [comment]
Mmmm... That isn't my rom... And it uses different kernel (it uses the outdated kitkat kernel) 

Maybe you can try flashing the modem.img from the lollipop stock rom for the bq Aquaris E4.5

**Comment by pinplex** [comment]
Ok. Where can I get the modem.img?
Cheers

**Comment by Pablito2020** [comment]
Flash it from stock lollipop rom.
Cheers!
Pablito2020

**Comment by pinplex** [comment]
Sorry, I can't figure out where to get the image. Do mean that [one](http://www.mibqyyo.com/de-download/2015/06/30/firmware-2-0-1-android-5-0/). Thank you!

**Comment by Pablito2020** [comment]
Yes, download the stock 2.1.0, open it with mtk flash tools and don't flash the full system, only the part that says modem (modem.img)

**Comment by Pablito2020** [comment]
Ohh It's device tree problem... RIL isn't working for me too! Will fix it soon
